# Generated by Django 3.2.5 on 2021-07-14 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('charmschool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('study_on', models.IntegerField(choices=[(0, 'จันทร์'), (1, 'อังคาร'), (2, 'พุธ'), (3, 'พฤหัสบดี'), (4, 'ศุกร์'), (5, 'เสาร์'), (6, 'อาทิตย์')])),
                ('place', models.CharField(max_length=100)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
    ]
