# Generated by Django 3.2.5 on 2021-07-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charmschool', '0002_groupdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupdata',
            options={'verbose_name_plural': 'Group Data'},
        ),
        migrations.AlterField(
            model_name='groupdata',
            name='study_on',
            field=models.CharField(choices=[('จันทร์', 'จันทร์'), ('อังคาร', 'อังคาร'), ('พุธ', 'พุธ'), ('พฤหัสบดี', 'พฤหัสบดี'), ('ศุกร์', 'ศุกร์'), ('เสาร์', 'เสาร์'), ('อาทิตย์', 'อาทิตย์')], max_length=10),
        ),
    ]
