# Generated by Django 3.2.5 on 2021-07-14 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charmschool', '0003_auto_20210714_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdata',
            name='description',
            field=models.CharField(max_length=256, verbose_name='คำอธิบาย'),
        ),
        migrations.AlterField(
            model_name='groupdata',
            name='end_time',
            field=models.TimeField(verbose_name='เลิกเรียน'),
        ),
        migrations.AlterField(
            model_name='groupdata',
            name='place',
            field=models.CharField(max_length=100, verbose_name='สถานที่เรียน'),
        ),
        migrations.AlterField(
            model_name='groupdata',
            name='start_time',
            field=models.TimeField(verbose_name='เริ่มเรียน'),
        ),
        migrations.AlterField(
            model_name='groupdata',
            name='study_on',
            field=models.CharField(choices=[('จันทร์', 'จันทร์'), ('อังคาร', 'อังคาร'), ('พุธ', 'พุธ'), ('พฤหัสบดี', 'พฤหัสบดี'), ('ศุกร์', 'ศุกร์'), ('เสาร์', 'เสาร์'), ('อาทิตย์', 'อาทิตย์')], max_length=10, verbose_name='วันที่เรียน'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group_ref',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
