# Generated by Django 3.2.5 on 2021-07-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('charmschool', '0005_auto_20210715_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
