# Generated by Django 3.2.5 on 2021-07-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charmschool', '0006_instructor_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='type',
            field=models.CharField(choices=[('อาจารย์ผู้สอน', 'อาจารย์ผู้สอน'), ('นักศึกษาผู้ช่วยสอน', 'นักศึกษาผู้ช่วยสอน')], max_length=30),
        ),
    ]
