# Generated by Django 3.2.5 on 2021-07-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charmschool', '0007_alter_instructor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='gender',
            field=models.CharField(choices=[('นาย', 'นาย'), ('นาง', 'นาง'), ('นางสาว', 'นางสาว'), ('อาจารย์', 'อาจารย์'), ('ผู้ช่วยศาสตราจารย์', 'ผู้ช่วยศาสตราจารย์'), ('รองศาสตราจารย์', 'รองศาสตราจารย์'), ('ศาสตราจารย์', 'ศาสตราจารย์')], max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('นาย', 'นาย'), ('นาง', 'นาง'), ('นางสาว', 'นางสาว'), ('อาจารย์', 'อาจารย์'), ('ผู้ช่วยศาสตราจารย์', 'ผู้ช่วยศาสตราจารย์'), ('รองศาสตราจารย์', 'รองศาสตราจารย์'), ('ศาสตราจารย์', 'ศาสตราจารย์')], max_length=20),
        ),
    ]
