# Generated by Django 3.2.5 on 2021-07-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('charmschool', '0008_auto_20210715_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_content',
            old_name='groups',
            new_name='visible_by',
        ),
        migrations.AddField(
            model_name='assignment',
            name='visible_by',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AddField(
            model_name='course_comment',
            name='visible_by',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
