# Generated by Django 3.2.5 on 2021-07-15 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charmschool', '0012_alter_course_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_comment',
            name='visible_by',
        ),
    ]
