# Generated by Django 3.2.5 on 2021-07-15 21:46

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('charmschool', '0013_remove_course_comment_visible_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='classwork',
            name='message',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='classwork',
            name='work',
            field=models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='classwork/<django.db.models.fields.related.OneToOneField>'),
        ),
    ]
