# Generated by Django 3.2.5 on 2021-07-16 09:12

from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('charmschool', '0015_alter_classwork_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classwork',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charmschool.assignment'),
        ),
        migrations.AlterField(
            model_name='classwork',
            name='work',
            field=models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='classwork/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
