# Generated by Django 3.2.5 on 2021-07-17 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charmschool', '0018_remove_student_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classwork',
            name='user',
        ),
        migrations.AddField(
            model_name='classwork',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charmschool.student'),
        ),
    ]
