# Generated by Django 3.2.5 on 2021-07-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charmschool', '0019_auto_20210717_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classwork',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
