# Generated by Django 3.2.5 on 2021-07-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charmschool', '0024_alter_classwork_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classwork',
            old_name='work',
            new_name='works',
        ),
    ]
