# Generated by Django 3.2.5 on 2021-07-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charmschool', '0025_rename_work_classwork_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='classwork',
            name='feedback',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='classwork',
            name='message',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
