# Generated by Django 3.2.5 on 2021-07-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charmschool', '0026_auto_20210729_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_content',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
