# Generated by Django 3.2.5 on 2021-09-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charmschool', '0027_course_content_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classwork',
            name='message',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
